import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  extractAnchors,
  extractIds,
  generateTraceTable,
} from './parser';

export interface RegenerateResult {
  written: boolean;
  path: string;
}

export function regenerateTrace(specDir: string): RegenerateResult {
  const reqPath = join(specDir, 'requirements.md');
  const desPath = join(specDir, 'design.md');
  const tracePath = join(specDir, 'trace.md');

  if (!existsSync(reqPath)) {
    throw new Error(`requirements.md not found in ${specDir}`);
  }
  if (!existsSync(desPath)) {
    throw new Error(`design.md not found in ${specDir}`);
  }

  const reqMd = readFileSync(reqPath, 'utf8');
  const desMd = readFileSync(desPath, 'utf8');

  const reqIds = extractIds(reqMd, 'REQ');
  const anchors = extractAnchors(desMd);
  const table = generateTraceTable(reqIds, anchors);

  const body = [
    '# Trace',
    '',
    'Auto-generated by `regenerateTrace`. Edit `requirements.md` or',
    '`design.md` and re-run instead of editing this file directly.',
    '',
    table,
    '',
  ].join('\n');

  writeFileSync(tracePath, body, 'utf8');
  return { written: true, path: tracePath };
}

export function isTraceStale(specDir: string): boolean {
  const tracePath = join(specDir, 'trace.md');
  if (!existsSync(tracePath)) return true;

  const traceMtime = statSync(tracePath).mtimeMs;
  for (const name of ['requirements.md', 'design.md']) {
    const p = join(specDir, name);
    if (!existsSync(p)) continue;
    if (statSync(p).mtimeMs > traceMtime) return true;
  }
  return false;
}
